#Tabuada
print('  -'*25)
print('| Bem vindo ao programa que gera tabuadas e resultados imediatamente!      |\n| Basta inserir o número que deseja que a tabuada desse valor será gerada. |')
print('  -'*25)
t = int(input('Digite o número para gerar a sua tabuada: '))
print('  -'*25)
print('{}x0={}'.format(t,t*0))
print('{}x1={}'.format(t,t*1))
print('{}x2={}'.format(t,t*2))
print('{}x3={}'.format(t,t*3))
print('{}x4={}'.format(t,t*4))
print('{}x5={}'.format(t,t*5))
print('{}x6={}'.format(t,t*6))
print('{}x7={}'.format(t,t*7))
print('{}x8={}'.format(t,t*8))
print('{}x9={}'.format(t,t*9))
print('{}x10={}'.format(t,t*10))
print('  -'*25)
print('|              Obrigado(a) por utulizar o nosso programa! :)                 | ')
print('  -'*25)