print('Bem vindo ao software beta de contagem, abaixo você terá que digitar um valor numérico para saber qual o dobro, \ntriplo e a raiz quadrada do valor dado em questão.')
print('----------------------------------------------------------------------------------------------------------------------')

n = int(input('Digite um valor: '))
print('O dobro de {} é {}.'.format(n,(n*2)))
print('O triplo de {} é {}. '.format(n,(n*3)))
print('A raiz quadrada de {} é aproximadamente {:.2f}.'.format(n,(n**0.5)))
print('-----------------------------------------------------------------------------------------------------------------------')
print('                                   Obrigado por utilizar o nosso programa beta! :)')
print('-----------------------------------------------------------------------------------------------------------------------')
